### ISSUE TITLE
Rethink the property inclusion relation

### ISSUE THREAD

**Issue by wytseoortwijn** [TNO/gLTSdiff#33]
The `Combiner::includes` method got removed from `Combiner` as part of #4, and was moved to the post processing rewriters instead. We should think of what we want to do with the inclusion relation. We could make it a separate operator, like combiners, hiders, etc. We could completely remove it, if it's only useful for the post-processing rewriters (which at the moment may not make effective use of such a relation). Perhaps it fits somewhere else somehow?

Probably first we should have a look at the mathematics of the post-processing rewriters, before deciding what to do here.

**Comment by dhendriks** [comment]
We actually have this as an operator now, see [Inclusion.java](../blob/334cdc56c0be6992ee04c3983374aeb66246238f/src/main/java/com/github/tno/gltsdiff/operators/inclusions/Inclusion.java). I'm closing this issue.
